-- fct_prescriptions の ESTIMATED_COST が DURATION_DAYS * UNIT_PRICE と一致することを検証する。
-- UNIT_PRICE が NULL の場合は ESTIMATED_COST も NULL であるべき。
SELECT
    LINK_PRESCRIPTION_HK,
    DURATION_DAYS,
    UNIT_PRICE,
    ESTIMATED_COST,
    DURATION_DAYS * UNIT_PRICE AS expected_cost
FROM {{ ref('fct_prescriptions') }}
WHERE UNIT_PRICE IS NOT NULL
  AND ESTIMATED_COST != DURATION_DAYS * UNIT_PRICE
