name: fusion
version: '1.0.0'

profile: fusion

flags:
  use_managed_iceberg: true
  use_materialization_v2: true

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  fusion:
    +schema: raw
    raw_airlines:
      +tags: ['travel']
    raw_destinations:
      +tags: ['travel']
    raw_flight_bookings:
      +tags: ['travel']
    raw_hotel_bookings:
      +tags: ['travel']
    raw_hotel_rate_history:
      +tags: ['travel']
    raw_hotels:
      +tags: ['travel']
    raw_travelers:
      +tags: ['travel']
    raw_departments:
      +tags: ['datavault']
    raw_doctors:
      +tags: ['datavault']
    raw_insurance_companies:
      +tags: ['datavault']
    raw_medications:
      +tags: ['datavault']
    raw_patient_insurance:
      +tags: ['datavault']
    raw_patients:
      +tags: ['datavault']
    raw_prescriptions:
      +tags: ['datavault']
    raw_visits:
      +tags: ['datavault']

models:
  fusion:
    staging:
      +materialized: view
      +schema: staging
      travel:
        +tags: ['travel']

    raw_vault:
      +materialized: incremental
      +schema: raw_vault
      +tags: ["datavault"]

    business_vault:
      +materialized: table
      +schema: business_vault
      +tags: ["datavault"]

    marts:
      +materialized: table
      +schema: marts
      datavault:
        +tags: ["datavault"]
      travel:
        +tags: ['travel']
