name: fusion
version: '1.0.0'

profile: fusion

flags:
  use_managed_iceberg: true
  use_materialization_v2: true

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  fusion:
    +schema: raw
    travel:
      +tags: ['travel']

models:
  fusion:
    staging:
      +materialized: view
      +schema: staging
      travel:
        +tags: ['travel']

    raw_vault:
      +materialized: incremental
      +schema: raw_vault
      +tags: ["datavault"]

    business_vault:
      +materialized: table
      +schema: business_vault
      +tags: ["datavault"]

    marts:
      +materialized: table
      +schema: marts
      datavault:
        +tags: ["datavault"]
      travel:
        +tags: ['travel']
