fusion:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: development
      schema: default
      host: dbc-f6e7e914-ce58.cloud.databricks.com
      http_path: /sql/1.0/warehouses/643b66d8a22ac512
      auth_type: oauth
      threads: 4
