name: dbt Merge

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - "transform/core/**"
      - ".github/workflows/dbt-merge.yml"

permissions:
  actions: read
  contents: read

env:
  SNOWFLAKE_ORGANIZATION_NAME: ${{ secrets.SNOWFLAKE_ORGANIZATION_NAME }}
  SNOWFLAKE_ACCOUNT_NAME: ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}
  SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

jobs:
  merge:
    name: Merge
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: dbt
    steps:
      - uses: actions/checkout@v6

      - name: dbt merge
        uses: ta93abe/dbt-jobs@v0.2.0
        with:
          type: merge
          adapter: snowflake
          project-dir: transform/core
          profile-dir: transform/core
          target: snowflake
          command: |
            dbt build --select state:modified+
          deferral: main
