name: dbt CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "transform/core/**"
      - ".github/workflows/dbt-ci.yml"

permissions:
  actions: read
  contents: read
  pull-requests: write

env:
  SNOWFLAKE_ORGANIZATION_NAME: ${{ secrets.SNOWFLAKE_ORGANIZATION_NAME }}
  SNOWFLAKE_ACCOUNT_NAME: ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    environment: dbt
    steps:
      - uses: actions/checkout@v6

      - name: Write Snowflake private key
        env:
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
        run: |
          (umask 177 && echo "$SNOWFLAKE_PRIVATE_KEY" > "$RUNNER_TEMP/snowflake_key.p8")
          echo "SNOWFLAKE_PRIVATE_KEY_PATH=$RUNNER_TEMP/snowflake_key.p8" >> "$GITHUB_ENV"

      - name: dbt ci
        uses: ta93abe/dbt-jobs@v0.2.0
        with:
          type: ci
          adapter: snowflake
          project-dir: transform/core
          profile-dir: transform/core
          target: snowflake
          command: |
            dbt build --select state:modified+
          deferral: main
          post-pr-comment: true
